### ISSUE TITLE
Beep plays for all server members

### ISSUE THREAD

**Issue by MrGriefs** [TFNRP/axonbody3#1]
The interval beeps plays for all players regardless of distance.

**Comment by NuclearWaste02** [comment]
I know mumble-voip and pma-voice have a specific way of getting distance between players that is not that resource intensive. It also features distant sound (e.g. quieter sounds the further you get away from the origin). Maybe you can look into this and implement it into the script. I personally have no clue on how this is achieved in those scripts, but it might be worth it looking into it.
[https://forum.cfx.re/t/release-mumble-voip-rp-radio/1083683]
[https://forum.cfx.re/t/release-voip-pma-voice-mumble-voip-alternative/1896255]

**Comment by MrGriefs** [comment]
I personally haven't been able to reproduce this issue myself, but it has been reported.
Sure, the method the script does may be resource intensive, however it only occurs every 2 minutes (may have further repercussion on servers with high player count).

I'll add that to the T4 tasks. Next time, please create an issue about it instead.

**Comment by NuclearWaste02** [comment]
Its not a seperate issue, its just a tip on this issue, reread my previous comment for clarification

**Comment by NuclearWaste02** [comment]
Is the bug fixed?

**Comment by MrGriefs** [comment]
@NuclearWaste02 Can't be reproduced / no reproduction steps

**Comment by NuclearWaste02** [comment]
Has this been tested with OneSync legacy/infinity? or tested without

**Comment by MrGriefs** [comment]
It's only been tested w/o.

**Comment by PerxG3** [comment]
This script is **_not_** OneSync compatible. Beep plays for all clients. We've resorted to disabling the function all-together.
