### ISSUE TITLE
axonbody3

### ISSUE THREAD

**Issue by AverilLuo** [TFNRP/axonbody3#14]
[ citizen-server-impl] Couldn't start resource axonbody3.
[         script:yarn] [yarn]	yarn install v1.22.5
[         script:yarn] [yarn]	info No lockfile found.
[         script:yarn] Error: [yarn]	warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[         script:yarn] [yarn]	[1/5] Validating package.json...
[         script:yarn] Error: [yarn]	error axonbody3@0.2.1: The engine "node" is incompatible with this module. Expected version "7". Got "16.9.1"
[         script:yarn] Error: [yarn]	error Found incompatible module.
[         script:yarn] [yarn]	info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[ citizen-server-impl] Building resource axonbody3 failed.
[ citizen-server-impl] Error data: yarn failed!

**Comment by MrGriefs** [comment]
The `yarn` resource is outdated and not supported. Do not use it, it conflicts with many other resources.
If, for whatever reason, you still need the `yarn` resource, you can patch it with my pull request here: https://github.com/citizenfx/cfx-server-data/pull/212
This will fix your issue.

Closing as wontfix
