### ISSUE TITLE
Allow Add_ace permissions to the script

### ISSUE THREAD

**Issue by Calub18** [TFNRP/axonbody3#4]
Hello, I think it would be amazing if the script allowed the use of ace permissions. This would allow only a certain group in a discord to use the script.

**Comment by MrGriefs** [comment]
This seems more than possible, I'll look into it in an hour or so.

**Comment by MrGriefs** [comment]
Thanks for the feedback. I've implemented ACL support, you can fetch/pull the changes on the main branch.
A release version will likely be tomorrow.
